-- Seed 25 bingo squares (developer-editable here)
insert into bingo_squares (position, label) values
  (0,  'Drank 2L of water today'),
  (1,  'Read 10 pages of a book'),
  (2,  'Exercised for 30 minutes'),
  (3,  'Cooked a meal from scratch'),
  (4,  'Called a friend or family member'),
  (5,  'Went for a walk outside'),
  (6,  'Meditated for 10 minutes'),
  (7,  'Got 8 hours of sleep'),
  (8,  'Tried something new today'),
  (9,  'Cleaned a room in your home'),
  (10, 'Wrote in a journal'),
  (11, 'Learned something interesting'),
  (12, 'FREE SPACE'),
  (13, 'Helped someone today'),
  (14, 'Ate a healthy breakfast'),
  (15, 'Spent time in nature'),
  (16, 'Did 10 minutes of stretching'),
  (17, 'Completed a task you''d been avoiding'),
  (18, 'Listened to a podcast or audiobook'),
  (19, 'Took a screen-free break'),
  (20, 'Practiced a hobby'),
  (21, 'Did a random act of kindness'),
  (22, 'Planned tomorrow the night before'),
  (23, 'Ate a piece of fruit'),
  (24, 'Went to bed before midnight');
