-- Full task pool — includes Free vakje (used as center square for all grids)
insert into bingo_squares (label) values
  ('Free vakje'),
  ('win 10 euro in sportbed'),
  ('Breakfast beers'),
  ('We zijn iemand kwijt'),
  ('selfie me randoms'),
  ('groep mensen/kinders 67 laten doen'),
  ('Roha wakker maken'),
  ('Win potje clash royal tegen Joran'),
  ('Koop een seksspeeltje'),
  ('Irish goodbye'),
  ('Open flesje bier op 5 verschillende manieren'),
  ('Roulette'),
  ('Start Le lac de connemara (mag thuis)'),
  ('Barfje'),
  ('Roha geragebait'),
  ('blaffen naar vreemden'),
  ('Iemand verliest GSM'),
  ('achter DJ booth'),
  ('Simon Wietjes'),
  ('Items stacken op iemand >= 0.5m'),
  ('een niet nederlandstalig Dekerk67 laten zeggen'),
  ('zon zien opkomen'),
  ('Vraag de weg aan iemand en ga de omgekeerde kant op'),
  ('doe YMCA -> vraag aan in een club'),
  ('Rene Le Blanc'),
  ('buitengesmeten uit cafe'),
  ('meer dan twee keer in 24 uur fast food'),
  ('er is ruzie wegens zetelke'),
  ('we verliezen waarborg'),
  ('Joran: Lloret dansmovekes'),
  ('Yente op uitstap met dame'),
  ('Adjes estafette'),
  ('vliegtuig applaus'),
  ('bij iemand met een hond vragen voor te aaien en dan hun aaien'),
  ('Gaslight iemand om ... te geloven'),
  ('Challenge van een vreemde krijgen en voltooien'),
  ('Slide in de DM''s'),
  ('Iemand verliest sleutels'),
  ('Adje met broek op uw enkels (openbaar)'),
  ('fight me rando''s'),
  ('airport beers'),
  ('Simon wietje'),
  ('Potje Brawl in de club'),
  ('Floris: vind ne Fransen'),
  ('Toertjes draaien rond borstel/stok dan pintje ad'),
  ('Happybd zingen voor een vreemden'),
  ('Vraag een selfie met een vreemde alzof ie bekend is'),
  ('Koop een souvenir'),
  ('Split the GG'),
  ('Drank voor 10u'),
  ('Badkamerfissa'),
  ('stripclub visit'),
  ('Tactisch fapje'),
  ('Floris: Kraslotjes in vliegtuig'),
  ('op de toog dansen?'),
  ('Slechte openingszin proberen'),
  ('Singles: naar de mama/papa bellen en zeggen dat je de liefde van uw leven ontmoet hebt'),
  ('in een fontein of vijver gaan'),
  ('Polonaise'),
  ('overtuig een dj om Belgische muziek te spelen');
