-- Full task pool — includes Free vakje (used as center square for all grids)
insert into bingo_squares (label) values
  ('Free vakje'),
  ('Uit een café worden buitengezet'),
  ('Singles: je mama of papa bellen en zeggen dat je de liefde van je leven hebt ontmoet'),
  ('Deel waarborg van het  appartement verliezen'),
  ('Op de toog dansen'),
  ('In een fontein of vijver gaan'),
  ('Een stripclub bezoeken'),
  ('Simon rookt een wietje'),
  ('Floris vindt een Fransman'),
  ('Een openingszin uitproberen gekozen door de groep'),
  ('Een liefdesverklaring doen'),
  ('€10 winnen op Sportbet'),
  ('YMCA aanvragen en meedoen in een club'),
  ('Een challenge krijgen van een vreemde en die voltooien'),
  ('Glas stelen uit een café'),
  ('Een DJ overtuigen om Belgische muziek te spelen'),
  ('De zon zien opkomen'),
  ('Een dance battle doen met een vreemde in de club'),
  ('Een adje doen met je broek op je enkels (in het openbaar)'),
  ('Een adjesestafette doen, minimaal 3 vs 3'),
  ('Een selfie nemen met random mensen'),
  ('Iemand die geen Nederlands spreekt "Dekerk67" laten zeggen'),
  ('We zijn iemand van de groep kwijt'),
  ('Iemand verliest zijn gsm'),
  ('Iemand verliest zijn sleutels'),
  ('Robbe wakker maken'),
  ('Ragebait iemand succesvol'),
  ('koop een kraslotje op het vliegtuig (als ze niet verkopen: Win 10 euro op sport bed)'),
  ('Doe de Joran Lloret-dansmoves bij de huzz'),
  ('De driesprong doen'),
  ('Iemand gaat op uitstap met een dame'),
  ('Blaffen naar vreemden'),
  ('Aan iemand met een hond vragen of je hem mag aaien en vervolgens de eigenaar aaien'),
  ('Happy Birthday zingen voor een vreemde'),
  ('Een potje Clash Royale winnen tegen Joran'),
  ('Een seksspeeltje kopen'),
  ('In een dame haar DM''s sliden'),
  ('Een groep van 67 mensen/kinderen "67" laten doen'),
  ('Minstens 0.5m aan spullen op iemand stapelen'),
  ('Yente een compleet absurd verhaal laten geloven'),
  ('Iemand de weg vragen en daarna bewust de andere kant uit wandelen'),
  ('Een selfie vragen met een vreemde alsof die bekend is'),
  ('Op één dag op 4 verschillende locaties een pint drinken'),
  ('Een bierflesje op 5 verschillende manieren openen'),
  ('10 toertijes tond een borstel/stok draaien tot je duizelig bent en daarna een pint adten'),
  ('Een Irish goodbye doen'),
  ('Een polonaise meedoen in de club'),
  ('Een badkamerfissa houden'),
  ('Roulette spelen (minimale inzet 10 euro)'),
  ('Le Lac du Connemara inzetten'),
  ('Airport beers'),
  ('Alcohol drinken vóór 10:00 uur'),
  ('Een souvenir kopen'),
  ('Een Belgisch biertje drinken in Praag'),
  ('Een potje Brawl Stars spelen in de club'),
  ('Breakfast beers'),
  ('Een tactisch fapje'),
  ('Applaudisseren wanneer het vliegtuig landt'),
  ('Split the G'),
  ('Drie of meer keren fastfood eten binnen 24 uur');